<a href="https://colab.research.google.com/github/bhavy404/UCS420p/blob/main/Assi4_420.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ASSIGNMENT - 4**  By- Bhavya Raj Singh

Q1. Create a NumPy 1D-array and perform operations
python
Copy code


In [1]:
import numpy as np


arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# a) Addition of 2 in all the element
add_arr = arr + 2
print("After adding 2 to all elements:", add_arr)

# b) Multiply 3 with all the elements
mul_arr = arr * 3
print("After multiplying all elements by 3:", mul_arr)

# c) Divide every element by 2
div_arr = arr / 2
print("After dividing all elements by 2:", div_arr)


Original array: [1 2 3 4 5]
After adding 2 to all elements: [3 4 5 6 7]
After multiplying all elements by 3: [ 3  6  9 12 15]
After dividing all elements by 2: [0.5 1.  1.5 2.  2.5]


Q2. Basic NumPy Array Operations

a) Reverse the NumPy array

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Reversed array: [5 4 6 3 2 1]


b) Find the most frequent value and their indices
python
Copy code


In [3]:
# i. Most frequent value and indices in x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_freq_value_x = np.bincount(x).argmax()
indices_x = np.where(x == most_freq_value_x)
print("Most frequent value in x:", most_freq_value_x)
print("Indices of the most frequent value in x:", indices_x[0])

# ii. Most frequent value and indices in y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq_value_y = np.bincount(y).argmax()
indices_y = np.where(y == most_freq_value_y)
print("Most frequent value in y:", most_freq_value_y)
print("Indices of the most frequent value in y:", indices_y[0])


Most frequent value in x: 1
Indices of the most frequent value in x: [0 5 7 8 9]
Most frequent value in y: 1
Indices of the most frequent value in y: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [4]:
import numpy as np

# Define 2-D array
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a) Access 1st row, 2nd column (indices start  0)
element_a = arr[0, 1]  # R 0, C 1
print("Element at 1st row, 2nd column:", element_a)

# b) Access 3rd row, 1st column
element_b = arr[2, 0]  # R 2, C 0
print("Element at 3rd row, 1st column:", element_b)


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q. 4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [5]:
import numpy as np


bhavya = np.linspace(10, 100, 25)


print("1-D Array:\n", bhavya)
print("Dimensions of the array:", bhavya.ndim)
print("Shape of the array:", bhavya.shape)
print("Total number of elements:", bhavya.size)
print("Data type of each element:", bhavya.dtype)
print("Total number of bytes consumed by the array:", bhavya.nbytes)


transposed_array = bhavya.reshape(25, 1)
print("\nTranspose using reshape():\n", transposed_array)


print("\nTranspose using .T:\n", bhavya.T)


print("\nCan we transpose a 1-D array using .T?")
print("No, the `.T` attribute does not transpose a 1-D array because it has no second axis.")
print("However, reshaping it first (e.g., into a 2-D array) allows `.T` to work.")


1-D Array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total number of elements: 25
Data type of each element: float64
Total number of bytes consumed by the array: 200

Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using .T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Can we transpose a 1-D array using .T?
No, the `.T` attribute does not transpose a 1-D array because it has no second axis.
However, reshaping it first (e.g., in

Q. 5 Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.


In [6]:
import numpy as np


ucs420_Bhavya = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])


mean_value = np.mean(ucs420_Bhavya)
median_value = np.median(ucs420_Bhavya)
max_value = np.max(ucs420_Bhavya)
min_value = np.min(ucs420_Bhavya)
unique_elements = np.unique(ucs420_Bhavya)


print("Original Array (ucs420_Bhavya):\n", ucs420_Bhavya)
print("Mean:", mean_value)
print("Median:", median_value)
print("Maximum:", max_value)
print("Minimum:", min_value)
print("Unique elements:", unique_elements)


reshaped_ucs420_Bhavya = ucs420_Bhavya.reshape(4, 3)
print("\nReshaped Array (4 rows x 3 columns):\n", reshaped_ucs420_Bhavya)


resized_ucs420_Bhavya = np.resize(ucs420_Bhavya, (2, 3))
print("\nResized Array (2 rows x 3 columns):\n", resized_ucs420_Bhavya)


Original Array (ucs420_Bhavya):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4 rows x 3 columns):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2 rows x 3 columns):
 [[10 20 30]
 [40 50 60]]
